// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cartographer/mapping/proto/submaps_options_2d.proto

#include "cartographer/mapping/proto/submaps_options_2d.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace cartographer {
namespace mapping {
namespace proto {
constexpr SubmapsOptions2D::SubmapsOptions2D(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : grid_options_2d_(nullptr)
  , range_data_inserter_options_(nullptr)
  , num_range_data_(0){}
struct SubmapsOptions2DDefaultTypeInternal {
  constexpr SubmapsOptions2DDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~SubmapsOptions2DDefaultTypeInternal() {}
  union {
    SubmapsOptions2D _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT SubmapsOptions2DDefaultTypeInternal _SubmapsOptions2D_default_instance_;
}  // namespace proto
}  // namespace mapping
}  // namespace cartographer
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_cartographer_2fmapping_2fproto_2fsubmaps_5foptions_5f2d_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_cartographer_2fmapping_2fproto_2fsubmaps_5foptions_5f2d_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_cartographer_2fmapping_2fproto_2fsubmaps_5foptions_5f2d_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_cartographer_2fmapping_2fproto_2fsubmaps_5foptions_5f2d_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::cartographer::mapping::proto::SubmapsOptions2D, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::cartographer::mapping::proto::SubmapsOptions2D, num_range_data_),
  PROTOBUF_FIELD_OFFSET(::cartographer::mapping::proto::SubmapsOptions2D, grid_options_2d_),
  PROTOBUF_FIELD_OFFSET(::cartographer::mapping::proto::SubmapsOptions2D, range_data_inserter_options_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::cartographer::mapping::proto::SubmapsOptions2D)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::cartographer::mapping::proto::_SubmapsOptions2D_default_instance_),
};

const char descriptor_table_protodef_cartographer_2fmapping_2fproto_2fsubmaps_5foptions_5f2d_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n3cartographer/mapping/proto/submaps_opt"
  "ions_2d.proto\022\032cartographer.mapping.prot"
  "o\0320cartographer/mapping/proto/grid_2d_op"
  "tions.proto\032<cartographer/mapping/proto/"
  "range_data_inserter_options.proto\"\311\001\n\020Su"
  "bmapsOptions2D\022\026\n\016num_range_data\030\001 \001(\005\022B"
  "\n\017grid_options_2d\030\002 \001(\0132).cartographer.m"
  "apping.proto.GridOptions2D\022Y\n\033range_data"
  "_inserter_options\030\003 \001(\01324.cartographer.m"
  "apping.proto.RangeDataInserterOptionsb\006p"
  "roto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_cartographer_2fmapping_2fproto_2fsubmaps_5foptions_5f2d_2eproto_deps[2] = {
  &::descriptor_table_cartographer_2fmapping_2fproto_2fgrid_5f2d_5foptions_2eproto,
  &::descriptor_table_cartographer_2fmapping_2fproto_2frange_5fdata_5finserter_5foptions_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_cartographer_2fmapping_2fproto_2fsubmaps_5foptions_5f2d_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_cartographer_2fmapping_2fproto_2fsubmaps_5foptions_5f2d_2eproto = {
  false, false, 405, descriptor_table_protodef_cartographer_2fmapping_2fproto_2fsubmaps_5foptions_5f2d_2eproto, "cartographer/mapping/proto/submaps_options_2d.proto", 
  &descriptor_table_cartographer_2fmapping_2fproto_2fsubmaps_5foptions_5f2d_2eproto_once, descriptor_table_cartographer_2fmapping_2fproto_2fsubmaps_5foptions_5f2d_2eproto_deps, 2, 1,
  schemas, file_default_instances, TableStruct_cartographer_2fmapping_2fproto_2fsubmaps_5foptions_5f2d_2eproto::offsets,
  file_level_metadata_cartographer_2fmapping_2fproto_2fsubmaps_5foptions_5f2d_2eproto, file_level_enum_descriptors_cartographer_2fmapping_2fproto_2fsubmaps_5foptions_5f2d_2eproto, file_level_service_descriptors_cartographer_2fmapping_2fproto_2fsubmaps_5foptions_5f2d_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_cartographer_2fmapping_2fproto_2fsubmaps_5foptions_5f2d_2eproto_getter() {
  return &descriptor_table_cartographer_2fmapping_2fproto_2fsubmaps_5foptions_5f2d_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_cartographer_2fmapping_2fproto_2fsubmaps_5foptions_5f2d_2eproto(&descriptor_table_cartographer_2fmapping_2fproto_2fsubmaps_5foptions_5f2d_2eproto);
namespace cartographer {
namespace mapping {
namespace proto {

// ===================================================================

class SubmapsOptions2D::_Internal {
 public:
  static const ::cartographer::mapping::proto::GridOptions2D& grid_options_2d(const SubmapsOptions2D* msg);
  static const ::cartographer::mapping::proto::RangeDataInserterOptions& range_data_inserter_options(const SubmapsOptions2D* msg);
};

const ::cartographer::mapping::proto::GridOptions2D&
SubmapsOptions2D::_Internal::grid_options_2d(const SubmapsOptions2D* msg) {
  return *msg->grid_options_2d_;
}
const ::cartographer::mapping::proto::RangeDataInserterOptions&
SubmapsOptions2D::_Internal::range_data_inserter_options(const SubmapsOptions2D* msg) {
  return *msg->range_data_inserter_options_;
}
void SubmapsOptions2D::clear_grid_options_2d() {
  if (GetArenaForAllocation() == nullptr && grid_options_2d_ != nullptr) {
    delete grid_options_2d_;
  }
  grid_options_2d_ = nullptr;
}
void SubmapsOptions2D::clear_range_data_inserter_options() {
  if (GetArenaForAllocation() == nullptr && range_data_inserter_options_ != nullptr) {
    delete range_data_inserter_options_;
  }
  range_data_inserter_options_ = nullptr;
}
SubmapsOptions2D::SubmapsOptions2D(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:cartographer.mapping.proto.SubmapsOptions2D)
}
SubmapsOptions2D::SubmapsOptions2D(const SubmapsOptions2D& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_grid_options_2d()) {
    grid_options_2d_ = new ::cartographer::mapping::proto::GridOptions2D(*from.grid_options_2d_);
  } else {
    grid_options_2d_ = nullptr;
  }
  if (from._internal_has_range_data_inserter_options()) {
    range_data_inserter_options_ = new ::cartographer::mapping::proto::RangeDataInserterOptions(*from.range_data_inserter_options_);
  } else {
    range_data_inserter_options_ = nullptr;
  }
  num_range_data_ = from.num_range_data_;
  // @@protoc_insertion_point(copy_constructor:cartographer.mapping.proto.SubmapsOptions2D)
}

void SubmapsOptions2D::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&grid_options_2d_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&num_range_data_) -
    reinterpret_cast<char*>(&grid_options_2d_)) + sizeof(num_range_data_));
}

SubmapsOptions2D::~SubmapsOptions2D() {
  // @@protoc_insertion_point(destructor:cartographer.mapping.proto.SubmapsOptions2D)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void SubmapsOptions2D::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete grid_options_2d_;
  if (this != internal_default_instance()) delete range_data_inserter_options_;
}

void SubmapsOptions2D::ArenaDtor(void* object) {
  SubmapsOptions2D* _this = reinterpret_cast< SubmapsOptions2D* >(object);
  (void)_this;
}
void SubmapsOptions2D::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void SubmapsOptions2D::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void SubmapsOptions2D::Clear() {
// @@protoc_insertion_point(message_clear_start:cartographer.mapping.proto.SubmapsOptions2D)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && grid_options_2d_ != nullptr) {
    delete grid_options_2d_;
  }
  grid_options_2d_ = nullptr;
  if (GetArenaForAllocation() == nullptr && range_data_inserter_options_ != nullptr) {
    delete range_data_inserter_options_;
  }
  range_data_inserter_options_ = nullptr;
  num_range_data_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SubmapsOptions2D::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 num_range_data = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          num_range_data_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .cartographer.mapping.proto.GridOptions2D grid_options_2d = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_grid_options_2d(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .cartographer.mapping.proto.RangeDataInserterOptions range_data_inserter_options = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_range_data_inserter_options(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* SubmapsOptions2D::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:cartographer.mapping.proto.SubmapsOptions2D)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 num_range_data = 1;
  if (this->_internal_num_range_data() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_num_range_data(), target);
  }

  // .cartographer.mapping.proto.GridOptions2D grid_options_2d = 2;
  if (this->_internal_has_grid_options_2d()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        2, _Internal::grid_options_2d(this), target, stream);
  }

  // .cartographer.mapping.proto.RangeDataInserterOptions range_data_inserter_options = 3;
  if (this->_internal_has_range_data_inserter_options()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        3, _Internal::range_data_inserter_options(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cartographer.mapping.proto.SubmapsOptions2D)
  return target;
}

size_t SubmapsOptions2D::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:cartographer.mapping.proto.SubmapsOptions2D)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .cartographer.mapping.proto.GridOptions2D grid_options_2d = 2;
  if (this->_internal_has_grid_options_2d()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *grid_options_2d_);
  }

  // .cartographer.mapping.proto.RangeDataInserterOptions range_data_inserter_options = 3;
  if (this->_internal_has_range_data_inserter_options()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *range_data_inserter_options_);
  }

  // int32 num_range_data = 1;
  if (this->_internal_num_range_data() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32SizePlusOne(this->_internal_num_range_data());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SubmapsOptions2D::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    SubmapsOptions2D::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SubmapsOptions2D::GetClassData() const { return &_class_data_; }

void SubmapsOptions2D::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<SubmapsOptions2D *>(to)->MergeFrom(
      static_cast<const SubmapsOptions2D &>(from));
}


void SubmapsOptions2D::MergeFrom(const SubmapsOptions2D& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:cartographer.mapping.proto.SubmapsOptions2D)
  GOOGLE_DCHECK_NE(&from, this);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_grid_options_2d()) {
    _internal_mutable_grid_options_2d()->::cartographer::mapping::proto::GridOptions2D::MergeFrom(from._internal_grid_options_2d());
  }
  if (from._internal_has_range_data_inserter_options()) {
    _internal_mutable_range_data_inserter_options()->::cartographer::mapping::proto::RangeDataInserterOptions::MergeFrom(from._internal_range_data_inserter_options());
  }
  if (from._internal_num_range_data() != 0) {
    _internal_set_num_range_data(from._internal_num_range_data());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SubmapsOptions2D::CopyFrom(const SubmapsOptions2D& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cartographer.mapping.proto.SubmapsOptions2D)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SubmapsOptions2D::IsInitialized() const {
  return true;
}

void SubmapsOptions2D::InternalSwap(SubmapsOptions2D* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SubmapsOptions2D, num_range_data_)
      + sizeof(SubmapsOptions2D::num_range_data_)
      - PROTOBUF_FIELD_OFFSET(SubmapsOptions2D, grid_options_2d_)>(
          reinterpret_cast<char*>(&grid_options_2d_),
          reinterpret_cast<char*>(&other->grid_options_2d_));
}

::PROTOBUF_NAMESPACE_ID::Metadata SubmapsOptions2D::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_cartographer_2fmapping_2fproto_2fsubmaps_5foptions_5f2d_2eproto_getter, &descriptor_table_cartographer_2fmapping_2fproto_2fsubmaps_5foptions_5f2d_2eproto_once,
      file_level_metadata_cartographer_2fmapping_2fproto_2fsubmaps_5foptions_5f2d_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace mapping
}  // namespace cartographer
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::cartographer::mapping::proto::SubmapsOptions2D* Arena::CreateMaybeMessage< ::cartographer::mapping::proto::SubmapsOptions2D >(Arena* arena) {
  return Arena::CreateMessageInternal< ::cartographer::mapping::proto::SubmapsOptions2D >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
